# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-11 02:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeckInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when_created', models.DateTimeField(auto_now_add=True)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sr.Deck')),
            ],
        ),
        migrations.CreateModel(
            name='FinishedReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.IntegerField()),
                ('answer_long_form', models.TextField(default=None)),
                ('when_reviewed', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduledReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when_scheduled', models.DateTimeField(auto_now_add=True)),
                ('when_due', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='summary',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='scheduledreview',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sr.Card'),
        ),
        migrations.AddField(
            model_name='scheduledreview',
            name='deck_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sr.DeckInstance'),
        ),
        migrations.AddField(
            model_name='finishedreview',
            name='scheduled_review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sr.ScheduledReview'),
        ),
    ]
