# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-12 00:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sr', '0004_auto_20170811_0456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='summary',
            field=models.CharField(default='', max_length=200),
        ),
    ]
