# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-12 03:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sr', '0005_auto_20170812_0030'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardRelationsSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ref', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='scheduler',
            old_name='reference',
            new_name='ref',
        ),
        migrations.AlterField(
            model_name='card',
            name='summary',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='deck',
            name='name',
            field=models.CharField(db_index=True, default='Orphaned', max_length=100),
        ),
        migrations.AlterField(
            model_name='finishedreview',
            name='answer_long_form',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='deckinstance',
            name='card_relations_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sr.CardRelationsSet'),
        ),
    ]
