# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-12 04:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sr', '0006_auto_20170812_0346'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardRelationsSchema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('ref', models.CharField(blank=True, default='', max_length=200)),
                ('blob', models.BinaryField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='cardrelationsset',
            name='blob',
            field=models.BinaryField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='cardrelationsset',
            name='deck',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='sr.Deck'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cardrelationsset',
            name='last_modified',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deck',
            name='last_added_to',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deck',
            name='last_modified_content',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cardrelationsset',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='cardrelationsset',
            name='ref',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='cardrelationsset',
            name='schema',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sr.CardRelationsSchema'),
        ),
    ]
