# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-12 05:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sr', '0007_auto_20170812_0458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardrelationsset',
            name='schema',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='sr.CardRelationsSchema'),
            preserve_default=False,
        ),
    ]
