# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-20 08:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sr', '0010_auto_20170820_0204'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deckinstance',
            name='reviews_done',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
