# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-20 09:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sr', '0011_auto_20170820_0852'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='deck',
            name='name',
            field=models.CharField(db_index=True, default='Orphaned', max_length=100, unique=True),
        ),
    ]
