# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-20 20:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sr', '0012_auto_20170820_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deckinstance',
            name='reviews_done',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='deckinstance',
            name='scheduler',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sr.Scheduler'),
        ),
    ]
