# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-20 20:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sr', '0013_auto_20170820_2008'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='deckinstance',
            unique_together=set([('deck', 'user')]),
        ),
    ]
