# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-31 05:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sr', '0014_auto_20170820_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledreview',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
