# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-31 05:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sr', '0015_scheduledreview_done'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='scheduledreview',
            index=models.Index(fields=['deck_instance', 'done'], name='sr_schedule_deck_in_ebebbe_idx'),
        ),
    ]
