# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-01 02:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sr', '0016_auto_20170831_0525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finishedreview',
            name='score',
            field=models.IntegerField(),
        ),
    ]
